#!/bin/sh
### BEGIN INIT INFO
# Provides:          fluent-bit
# Required-Start:    $local_fs $network $named $time $syslog fetch-config
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fluent Bit
# Description:       Fluent Bit is a Fast and Lightweight Log processor and forwarder
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=td-agent-bit
DESC="FluentBit Service"
LOG_DIR=/var/log/containers
LOGFILE="$LOG_DIR/td-agent-bit.log"
FLUENT_BIT_VERSION=3.2.10@sha256:d6dec000c4929a439562525728c708f6e99800d7ddc82efd6aa4f45f3a20b562
FLUENT_BIT_ENV_FILE=/etc/td-agent-bit/aws-auth
FLUENT_BIT_CONFIG_FILE=/etc/td-agent-bit/td-agent-bit.conf

FLUENT_BIT_USER=fluentbit
FLUENT_BIT_GROUP=fluentbit

start_fluent_bit() {
    podman run -dt --rm --restart on-failure --name $NAME \
        --user $(id -u $FLUENT_BIT_USER):$(id -g $FLUENT_BIT_GROUP) \
        -v $FLUENT_BIT_CONFIG_FILE:/td-agent-bit.conf \
        --log-opt path=$LOGFILE --log-opt max-size=10mb \
        --env-file $FLUENT_BIT_ENV_FILE \
        docker.io/fluent/fluent-bit:$FLUENT_BIT_VERSION -c /td-agent-bit.conf
}

start() {
    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo

    install -d -m 755 $LOG_DIR 
    touch $LOGFILE
    chown fluentbit:fluentbit $LOGFILE

    if [ ! -f "$FLUENT_BIT_CONFIG_FILE" ]; then
        echo "Error: Configuration file $FLUENT_BIT_CONFIG_FILE not found" >> $LOGFILE
        return 1
    fi

    start_fluent_bit
    echo "$NAME."
}

stop() {
    echo "Stopping $DESC" | tee -a /var/volatile/system-api.fifo
    podman stop $NAME
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload}" >&2
        exit 1
        ;;
esac

exit 0
